# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: servicos_dispositivos.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'servicos_dispositivos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bservicos_dispositivos.proto\x12\x0c\x64ispositivos\"+\n\x14LigarDesligarRequest\x12\x13\n\x0binterruptor\x18\x01 \x01(\x08\" \n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1f\n\rBrilhoRequest\x12\x0e\n\x06\x62rilho\x18\x01 \x01(\x05\"&\n\x0c\x43\x61nalRequest\x12\x16\n\x0e\x63\x61nalEscolhido\x18\x01 \x01(\x05\"2\n\x12TemperaturaRequest\x12\x1c\n\x14temperaturaEscolhida\x18\x01 \x01(\x05\x32\xa8\x01\n\x0eLampadaService\x12Q\n\rLigarDesligar\x12\".dispositivos.LigarDesligarRequest\x1a\x1c.dispositivos.StatusResponse\x12\x43\n\x06\x42rilho\x12\x1b.dispositivos.BrilhoRequest\x1a\x1c.dispositivos.StatusResponse2\xa8\x01\n\x10TelevisaoService\x12Q\n\rLigarDesligar\x12\".dispositivos.LigarDesligarRequest\x1a\x1c.dispositivos.StatusResponse\x12\x41\n\x05\x43\x61nal\x12\x1a.dispositivos.CanalRequest\x1a\x1c.dispositivos.StatusResponse2\xb9\x01\n\x15\x41rCondicionadoService\x12Q\n\rLigarDesligar\x12\".dispositivos.LigarDesligarRequest\x1a\x1c.dispositivos.StatusResponse\x12M\n\x0bTemperatura\x12 .dispositivos.TemperaturaRequest\x1a\x1c.dispositivos.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'servicos_dispositivos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIGARDESLIGARREQUEST']._serialized_start=45
  _globals['_LIGARDESLIGARREQUEST']._serialized_end=88
  _globals['_STATUSRESPONSE']._serialized_start=90
  _globals['_STATUSRESPONSE']._serialized_end=122
  _globals['_BRILHOREQUEST']._serialized_start=124
  _globals['_BRILHOREQUEST']._serialized_end=155
  _globals['_CANALREQUEST']._serialized_start=157
  _globals['_CANALREQUEST']._serialized_end=195
  _globals['_TEMPERATURAREQUEST']._serialized_start=197
  _globals['_TEMPERATURAREQUEST']._serialized_end=247
  _globals['_LAMPADASERVICE']._serialized_start=250
  _globals['_LAMPADASERVICE']._serialized_end=418
  _globals['_TELEVISAOSERVICE']._serialized_start=421
  _globals['_TELEVISAOSERVICE']._serialized_end=589
  _globals['_ARCONDICIONADOSERVICE']._serialized_start=592
  _globals['_ARCONDICIONADOSERVICE']._serialized_end=777
# @@protoc_insertion_point(module_scope)
